---
layout: course
title:  "Speech Perception"
subtitle: "co-taught with Patrice S. Beddor"
date:   2019-07-15 17:21:16
categories: teaching "speech perception"
---
Experimental speech perception, which spans a period of more than 70 years, investigates how listeners interpret the input acoustic signal as linguistic forms. From the discipline's earliest years, researchers recognized that the acoustic signal is highly variable and that perceptual processing is more complex (and interesting!) than a simple one-to-one mapping between acoustic property and linguistic percept. Yet, despite this complexity, humans are highly accurate perceivers of the intended speech in typical conversational interactions.

This course will provide students with an overview of the dominant theories of speech perception and the theoretical issues that drive empirical studies, including the fundamental question of whether speech perception differs from other types of auditory processing. Readings, course discussions, and hands-on experience with classic speech perception experiments will guide students through the field's evolution from an emphasis on psychoacoustics and the acoustic signal to an appreciation for the structured nature of variation and how it informs perception. We will discover together that, while listeners closely attend to the structured variation, individual listeners do so in ways that depend on their linguistic experiences, social expectations, processing style, and more. Listeners are active participants who recruit multiple cognitive resources in achieving malleable, dynamic perception.

- Background: Students may find having some familiarity with acoustic phonetics helpful (although this background is not essential for this course). Excellent chapters include these:
  - Raphael, L.J., Borden, G.J., & Harris, K.S. 2011. Speech Science Primer. Philadelphia, PA: Wolters Kluwer/Lippincott. 6th edition, chapters 5 & 6.
  - Reetz, H. & Jongman, A. 2008. Phonetics: Transcription, Production, Acoustics, and Perception. Malden, MA: Wiley-Blackwell. 1st edition, chapters 9 & 10.
  - Ladefoged, P. & Johnson, K. 2015. A Course in Phonetics. Boston, MA: Thomson. 6th edition, chapter 8.
- Readings: There is no expectation that you will have time, during the busy weeks of the Institute, to read more than one paper per class meeting. For each class meeting, the syllabus marks the most strongly recommended reading in bold. (You might view other readings as background material that you may wish to consult after the Institute is over.)
- Writing assignment: A roughly 500 word research prospectus for an original, theoretically motivated speech perception experiment or a two-page critical assessment, supported by experimental evidence from the literature, of a well-defined issue in speech perception. Students are encouraged to get together with Pam or Kevin to run their ideas past us before submitting their paper, which is due 7-18 (11:59 pm).


### Part 1: Perception of variability due to phonetic context

- **June 24**: Phonetic variation: noise in signal that listeners tune out or useful information that facilitates perception? Broad theoretical approaches to perception of acoustic variation

  Speech perception research has always drawn attention to acoustic variation and the complex relation between acoustic signal and linguistic percept. Interpretation of some experimental findings, such as categorical perception (a phenomenon we'll experience ourselves), has emphasized listeners' ability to seemingly ignore or "abstract away" phonetic details in making perceptual judgments. Yet other findings show listeners to be malleable perceivers who are sensitive to fine-grained phonetic variation.
	Readings: Liberman et al. 1957, McMurray et al. 2002

- **June 27**: Perceiving coarticulatory variation
  Coarticulation is a main source of contextual variation: due to overlapping articulatory movements, the acoustic realizations of consonants and vowels differ depending on the phonetic context in which they occur. Listeners accommodate or "compensate" for coarticulation, attributing the acoustic effects of overlapping gestures to their coarticulatory source. … Or do they? Interpretation of compensatory responses has been controversial for 35 years. We'll discuss the relevant evidence in order to better understand why compensation for coarticulation has remained an important testing ground for gesturalist vs. auditory theories of speech perception.
	Readings: Mann 1980, Lotto & Kluender 1998, Fowler 2006, Lotto & Holt 2006

- **July 1**: Gesturalist theories of speech perception: Motor Theory and Direct Realism

  Theories of speech perception differ in their conception of the information that listeners recover from the acoustic signal. Gesturalist theories posit that the recovered information is for vocal tract actions. Early empirical motivation for Motor Theory included findings (such as from categorical perception) consistent with perception paralleling articulation more closely than acoustics. For Direct Realism, perception of vocal tract actions follows from the more general perspective that perceptual systems perceive the events that cause the lawful structure in the input signal. Our discussion of these theories will consider not only the nature of perceived information but also the fundamental question: Is speech (perception) special?
	Readings: Liberman & Mattingly 1985, Fowler 1996, Whalen 2019

- **July 3**: (Wednesday) Perceivers as producers of contextual variation

  Phonetic theory aims to explain the principles of human speech production and perception that underlie transmission of a linguistic message: speakers produce articulations with acoustic consequences that convey the planned linguistic information to listeners. Thus, understanding the relation between perception and production is central to phonetic theory. It is similarly central to theories of the phonetics of sound change, many of which assume a tight perception-production link such that individual listeners' percepts are publicly manifested in their own productions. We will end this first half of the course by considering listeners as speakers, innovators, and members of speech communities whose speaker-specific production of contextual variation reflects their listener-specific perceptual use of that variation.
  Readings: Ohala 1981, Beddor 2009, Beddor et al. 2018


### Part II: Perception of variability due to talker differences

- **July 8**: Auditory and Exemplar theories of speech perception
  To begin the second half of the course, we will return to our investigation of the ways in which theories of speech perception construe the task.  Specifically, what is the object of perception? In contrast to gesturalist theories, auditory theories posit that the recovered information from an acoustic signal is the auditory signal itself. But, as with gestural theories, we still face the difficulty of how listeners map highly variable acoustic information onto (perhaps) surprisingly consistent percepts.  Exemplar theories (Goldinger and Johnson in this week's readings) propose one possible solution to this mapping problem by suggesting that listeners draw on their detailed experience with language use to process new experiences with speech.
  Readings: Diehl et al. 2004, Goldinger 1998, Docherty & Foulkes, 2014

- **July 11**: Approaches to vowel perception:
  Whether gestural, auditory, or exemplar, any theory of speech perception must explain how listeners perceive particular vowel qualities and virtually all speech perception researchers agree on what the basic questions are and what evidence about vowel perception must be explained in a satisfactory theory.  Today we will consider evidence and theories that have emerged over time from Joos 1947 to work that is accepted but not yet available in print.  We will begin with the acoustics and articulation of vowels, experience some vowel perception studies first hand, and think together about what the different theories we have explored might have to say about vowels.
Readings: Peterson & Barney 1952, Ladefoged & Broadbent 1957, Strange & Jenkins 2013, Johnson 2006, McGowan and Babel 2020

- **July 15**: Perceiving social variation: perceptions of identity among native speakers and listeners
  Gender is a main source of variation attributable to talker differences: due to differences in vocal fold thickness, vocal tract length, but also social expectations. Listeners accommodate gender differences, attributing the acoustic effects of gender difference to their biological source. … Or do they? Listeners' use of gender (and sexuality) information in the voice has been of central interest to sociophonetic perception and to speech perception research more generally for decades.  We will discuss some of the key evidence and implications for theory.
Readings: Strand & Johnson 1996, Clopper & Pisoni 2004, Mack & Munson 2010, Sumner et al. 2014

- **July 18**: Perceiving social variation: why do people believe non-native speakers are difficult to understand?
  Linguists and non-linguists share a common belief that understanding the speech of non-native speakers is unusually difficult.  As theorists and researchers we should always be wary of our own unexplored assumptions and biases, but perhaps this is even more true when these assumptions and biases can lead otherwise well-intentioned scientific research to reinforce existing inequality.  In today's class we will attempt to bring everything we have learned so far about speech perception, assessing a theoretical position, and listeners' use of sources of variability in speech to assess the extent to which non-native speech is, or is not, especially problematic for listeners.
  Readings: Rubin 1992, McGowan 2015, Baese Berk 2019 (popular science article, short and accessible) 

