# Site settings
title: Kevin B. McGowan
email: kbmcgowan@stanford.edu
description: linguist, phonetician, nerd
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kbmcgowan.github.io" # the base hostname & protocol for your site

twitter_username: kbmcgowan
github_username:  kbmcgowan

markdown: kramdown
highlighter: rouge

permalink: /blog/:year/:month/:day/:title.html

gems:
  - jekyll-sitemap

paginate: 7
paginate_path: "/blog/page:num/"
