# Site settings
title: Kevin B. McGowan
email: kbmcgowan@uky.edu
description: linguist, phonetician, nerd
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kbmcgowan.github.io" # the base hostname & protocol for your site

github_username:  kbmcgowan

markdown: kramdown
highlighter: rouge

permalink: /blog/:year/:month/:day/:title.html

gems:
  - jekyll-sitemap

paginate: 7
paginate_path: "/blog/page:num/"

theme: jekyll-theme-tactile
#remote_theme: alshedivat/al-folio
#plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have one
