project:
  type: website

website:
  title: Kevin B. McGowan
  description: linguist, phonetician, nerd
  favicon: favicon.ico
  navbar:
    right:
      - href: index.qmd
        text: home
      - research/index.qmd
      - teaching/index.qmd
      - stuff/index.qmd
      - cv/index.qmd

execute:
  freeze: auto
  
format:
  html:
    theme: [journal, yeti-colors.scss]
    fontsize: 1.1em
    # lumen, pulse, zephyr, flatly
    css: styles.css
    toc: false
    format:
    include-in-header:
      - text: |
          link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
          <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
          <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
          <link rel="manifest" href="/site.webmanifest">



