project:
  type: website

website:
  title: Kevin B. McGowan
  description: linguist, phonetician, nerd
  navbar:
    right:
      - href: index.qmd
        text: home
      - research/index.qmd
      - teaching/index.qmd
      - stuff/index.qmd
      - cv/index.qmd

execute:
  freeze: auto
  
format:
  html:
    theme: [journal, yeti-colors.scss]
    fontsize: 1.1em
    # lumen, pulse, zephyr, flatly
    css: styles.css
    toc: false



