---
layout: course
title: "Lin 211: Introduction to the Study of Language"
date:   2026-07-30 10:55:16
format: html
editor: source
categories: introduction
---

Fall 2026\
Whitehall Classroom Building 110\
MW 10:00 - 10:50 am\

### Kevin B. McGowan
Associate Professor, Linguistics\
kbmcgowan\@uky.edu\
 \
My **drop-in office hours** will be held in my office (Patterson Office Tower, room 1669). Please do not hesitate to come meet with me if you have any questions at all.

- M 11:00 - 12:00pm \ (after class)
- T 3:00 - 4:00 pm \
- or [make an appointment](https://appt.link/meet-with-kevin-mcgowan-8HaU92A1) if the normal drop-in times do not fit your schedule. \

## Teaching Assistants (Discussion Leaders)

::::: columns
::: {.column width="50%"}

### Grace Anderson
Doctoral Student, Linguistics\
 \
- Sections: 003, 005 \
- Office Hours: TBD \

### Jocelyn Brown
Doctoral Student, Linguistics\
 \
- Section: 006\
- Office Hours: TBD \


### Sarah Ertel
Doctoral Student, Linguistics\
 \
- Sections: 001, 004\
- Office Hours: TBD \


:::

::: {.column width="50%"}

### Nora O'Brien
Doctoral Student, Linguistics\
 \
- Section: 002 \
- Office Hours: MW 11:00am - 12:00pm \


### Stella Takvoryan\
Doctoral Student, Linguistics\
stakvoryan\@uky.edu\
 \
- Section: 007 \
- Office Hours: W 11:00am-12:00pm & F 10:00 - 11:00am  \
:::
:::::

## Course Description

This course is designed to give students a broad introduction to the field of linguistics from the perspective of language users. As native users of at least one spoken or signed language, students are already in some ways experts in how language works. This course will explore the beliefs about and perceptions of language that they already possess and build upon this knowledge by comparing popular notions about language with those developed in linguistic science, paying attention to the contributions of popular belief as well as the differences between them and scientific findings. [This course counts for the UK Core Inquiry in the Social Sciences requirement.]

## Course Prerequisites

There are no prerequisites for this course.

## Required Materials
_Linguistics: Why it matters_ by Geoffrey Pullum. 2018. Polity press.

Additional readings will be made available on Canvas.


## Associated Expenses

There are no associated expenses for this course.

## Activities Outside of Regular Class Meetings

There are no required interactions outside of class.

##  Skill & Technology Requirements 

**Canvas**: We will use Canvas for our course website, and a lot of information will be made available there. You can go directly to [https://uk.instructure.com/](https://uk.instructure.com/) to sign in. Canvas has an app that comes highly recommended. You can also find helpful instructions at [http://www.uky.edu/canvas/](http://www.uky.edu/canvas/). Please log on to Canvas as soon as possible, and contact the instructor if you encounter any difficulty doing so. You should check Canvas regularly for information relating to this class.

**Required Devices**: Because we will be using Canvas as part of the course delivery, students will be required to bring a laptop, tablet computer, or mobile phone to class. Please come to class prepared to use this technology (i.e., know how it works, has enough battery life), but please make sure it is only used for the purposes of the lecture (i.e., do not use the device for Instagram, TikTok, Generative AI, or other non-class-related activities). Within Canvas, we will be using (among other things) Echo360 ALP, an app that we will use for class polling and engagements. Students will be able to submit answers to questions asked in class using their own device. If you have questions or concerns about this aspect of the course, please see the instructor immediately.

**Technical assistance**: For urgent needs, contact ITS Customer Services 24/7 at 859-218-HELP (4357). For non-urgent matters, visit the ITS web page at [https://its.uky.edu/](https://its.uky.edu/) to submit a Customer Service Assistance Request.

## Student Learning Outcomes

After successful engagement with the material in this course, you will be able to:

- Define and distinguish different theoretical approaches to linguistics,
- Apply their understanding of methods and ethics of inquiry in linguistics to create and advance linguistic knowledge,
- Demonstrate the ability to identify and use appropriate information resources in linguistics to substantiate evidence-based claims,
- Recognize how linguistic knowledge influences society (and vice versa),
- Identify well-formulated questions pertinent to linguistics and employ appropriate approaches to identify reasonable research strategies that could speak to that question.

## Tentative Course Schedule

The last day to add a class is Friday, August 28th. Midterm grades are due to the Registrar by Monday, October 26th. Though there will not be a traditional exam, we will use the final exam time for the final assignment (see below). Our final exam time is **Monday, December 14th, 10:30 AM - 12:30 PM**. For UK’s full exam schedule, see
[https://registrar.uky.edu/examination-schedules](https://registrar.uky.edu/examination-schedules).

The following dates are approximate, and dates are subject to change. **Pullum** refers to readings in the course textbook while readings marked **Canvas** are available on, or linked from, Canvas.  Please note that readings are real assignments and a core part of the course. Failure to do them is a waste of your tuition money and time.

| Date | Theme | Reading(s) Due |
|------|-------|-------------|
| **Getting Started** | | (weeks 1 - 3) |
|	Monday, Aug 24th	| Getting started: What is this course?	|	|
|	Wednesday, Aug 26th	| What is linguistics anyway?	|	|
|	Monday, Aug 31st	| What is language?	| Pullum: Chapter 1 |
|	Wednesday, Sep 2nd	| How many languages are there? | Canvas: How Many?	|
|	Monday, Sep 7th	| Labor Day	| (no class)	|
|	Wednesday, Sep 9th	| Where does language come from? 	|	|
| **Bits & Pieces** | | (weeks 4 - 7) |
|	Monday, Sep 14th	|	Spotlight Lecture: What is linguistics research? |	|
|	Wednesday, Sep 16th	| What is a word?	| Pullum: Chapter 3	|
|	Monday, Sep 21st	| How do words get their meaning?	|	|
|	Wednesday, Sep 23rd	| Is slang legit?	| Pullum: Chapter 2	|
|	Monday, Sep 28th	| Why are some words “bad words”?	|	|
|	Wednesday, Sep 30th	| Who says “pop” and why?	| Pullum: Chapter 4	|
|	Monday, Oct 5th	| Where do dialects come from?	|	|
|	Wednesday, Oct 7th	| What is the prettiest language?	|	Canvas: Perceptual Dialectology |
| **Language in the world** | | (weeks 8 - 13) |
|	Monday, Oct 12th	| Spotlight lecture: What methods and ethics of inquiry are used?	|	|
|	Wednesday, Oct 14th	| How do kids learn to talk?	| Canvas: Nine Ideas	|
|	Monday, Oct 19th	| How does bilingualism work?	|	|
|	Wednesday, Oct 21st	| Why is it hard to learn other languages? | Canvas: Bilingual Brain	|
|	Monday, Oct 26th	| Fall Break	| (no class)	|
|	Wednesday, Oct 28th	| How is writing different from speaking?	|	|
|	Monday, Nov 2nd	| 🤷	|	Pullum: Chapter 5 |
|	Wednesday, Nov 4th	| Why can’t Siri pronounce my name?	|	|
|	Monday, Nov 9th	| How do computers help with language?	|	|
|	Wednesday, Nov 11th	|	Are chatbots real? | Canvas: Bender |
|	Monday, Nov 16th	|	|	|
|	Wednesday, Nov 18th	| Spotlight lecture: How do we find relevant linguistics sources?	| 	|
| **Language & culture** | | (weeks 14 - 15) |
|	Monday, Nov 23rd	| Are actors good at dialects?	|	Canvas: Interview with a dialect coach |
|	Wednesday, Nov 25th	| Thanksgiving	| (no class)	|
|	Monday, Nov 30th	| Can you make your own language?	|	|
|	Wednesday, Dec 2nd	| Do animals use language?	| Canvas: LA Times (2018)	|
| **So what?** | | (week 16) |
|	Monday, Dec 7th	| Who really uses this stuff?	| Pullum: Conclusion	|
|	Wednesday, Dec 9th	| Why Linguistics?	|	|
: Tentative schedule (dates are approximate) {.striped .hover}

## Tenative Discussion Section Plans

| Date | Activity/Assignment |
|------|-------|
|       Friday, Aug 28th        | Meet your TA    |
|       Friday, Sep 4th        | Quiz 1          |       
|       Friday, Sep 11th        | Quiz 2          |
|       Friday, Sep 18th        | Quiz 3          |
|       Friday, Sep 25th        | Quiz 4          |
|       Friday, Oct 2nd        | Quiz 5          |
|       Friday, Oct 9th        | Quiz 6          |
|       Friday, Oct 16th        | Quiz 7          |
|       Friday, Oct 23rd        | Data Collection |
|       Friday, Oct 30th        | Quiz 8          |
|       Friday, Nov 6th        | Quiz 9          |       
|       Friday, Nov 13th        | Quiz 10         |
|       Friday, Nov 20th        | Quiz 11         |
|       Friday, Nov 27th        | Thanksgiving (no class) |
|       Friday, Dec 4th         | Quiz 12         |
: Discussion section dates and activities {.striped .hover}

## Course Activities, Assignments, Exams

### Course Activities and Exams

The following assignments will be used to determine your grade in the course. Below the descriptions, you will see the weight that each assignment type carries for your grade. Due dates for these assignments (subject to change) are listed in Canvas.

- **Quizzes (30%)**: Each week in discussion sections (beginning during the second week of classes), students will complete a short quiz in Canvas over the material that has been covered in lecture and in the course readings. These quizzes are not designed to be difficult; rather, their purpose is to ensure that everyone is keeping up with the readings and understands the material covered in the course. There will be 12 quizzes given, and the lowest two (2) quiz grades will be dropped. Each quiz is worth 3% of your final grade, for a total of 30% of the final grade. YOU WILL NEED YOUR DEVICE TO ACCESS CANVAS!
- **Observation notes (15%)**: Beginning in the second week of classes, students will keep an online language observation journal. More details will be provided, but students must listen to language as it is being used in their communities and document what they hear. It should not be necessary to record such interactions (and doing so surreptitiously would not be ok). Students will need to note the who, what, where, when, why, and how of what they heard, paying particular attention to what might make the interaction of interest to linguists. Observation is about careful and thoughtful attention to detail. Students must go beyond how they typically listen to conversations and try to listen like a linguist. There will be 6 entries to submit during the semester, and the lowest grade will be dropped. Each journal entry is worth 3% of your final grade, for a total of 15% of the final grade. YOU MUST NOT USE AI TO GENERATE THESE!
- **Data Collection (20%)**: Near the middle of the semester, students will complete a large-scale assignment  involving the collection of linguistic data. More details will be provided, but students will collect data and be asked a number of questions to show that they understand aspects of linguistic research methods and ethics as explored in the class. Students will have time to work on the assignment in discussion on the due date, but the assignment will require additional time outside of class to complete. This assignment is worth 20% of the final grade.
- **Data Analysis (25%)**: Near the end of the semester, students will complete another large-scale assignment. This assignment will involve the analysis of the linguistic data collected near midterm. More details will be provided, but students will demonstrate their ability to identify an appropriate research question related to that data. Students will also provide relevant academic sources that could be used to better understand the data and the research question. Students will have time to work on the assignment during the scheduled exam time for their section, but the assignment will require additional time outside of the exam time to complete. This assignment is worth 25% of the final grade.
- **Participation (10%)**: Students are expected to attend each class (lecture and discussion) and to have done any reading or other work assigned for that day. In discussion, participation will be gauged by attendance, participation in class activities, and/or submission of assignments, as required. In lecture, participation in the class will be gauged by responses to participation questions that are sprinkled throughout the lectures. Students will be able to submit answers in class through Echo360 using a laptop, tablet, or mobile phone. The grade will be based on whether you were able to participate on a given day. If you have questions or concerns about this aspect of the course, please see the instructor immediately. Participation is worth 10% of the final grade.

| Activity | Percentage |
|:---------|:----------:|
| Quizzes (10): | 30% |
| Observation notes (5): | 15% |
| Data Collection: | 20% |
| Data Analysis: | 25% |
| Participation: | 10% |
: Grade Breakdown {.striped .hover}


## Grading Scale

Below is the grading scale that will be used in the course. Canvas is set to automatically configure grades based on this scale.

| Percentage of available credit earned | Letter Grade |
|-----------:|:----:|
| 90 ≤ 100% | A |
| 80 <  90% | B |
| 70 <  80% | C |
| 60 <  70% | D |
|    <  60% | E |

## Midterm Grades

For undergraduates, midterm grades will be posted in myUK by the deadline published in the [Academic Calendar](https://registrar.uky.edu/calendars) which, for our course, is Monday, October 26th.

## Attendance Policy and Excused Absences
- **Lecture**: There will be participation questions for students to complete in Echo360 during each class, and failure to answer these questions will cause your participation grade to suffer. Only students who are present in lecture will be able to complete these questions. To account for the fact that students may have excused absences (but these are quite difficult to track in a large lecture class), occasional opportunities to make up participation points will be given to all throughout the semester. Additionally, quizzes in discussion are based on lecture, so failure to attend class will likely result in lower quiz scores.
- **Discussion Sections**: Attendance at Friday discussion is mandatory, as these sessions involve all class quizzes. Unexcused absences will result in a zero grade for the missed quiz. TAs will take attendance in each discussion session. Students need to notify their TA of absences prior to class when possible. Acceptable reasons for an excused absence are listed here: https://provost.uky.edu/proposals/guidance-course-proposals/standard-academic-policy-statements. See also the policy regarding religious observances
- **Excuse notes will be required for any missed discussion**, and make-up work will only be allowed if you have an excused absence. If you are absent, it is your responsibility to coordinate with your TA to make up the missed work. You are responsible for all material covered in class, even if your absence is excused. You are expected to submit your excuse note within one week of your return to class after the absence. Upon submission of the excuse note, you will only have one week to make up any missed assignments. After this time, your missed assignments will become zero grades. We will be very strict about this timeline!

## Verification of Absences

Students will be asked to verify their absences for them to be considered excused. See above for details.

## Assignment Submissions
Most assignments will be submitted online, primarily through Canvas.

## Returning Assignments to Students

Feedback on most assignments will be provided online, primarily through Canvas.

## Late Assignments

Late assignments will be accepted only in the event of documented excused absences. 

## Assignments Due during Prep Week 

No assignments will be due during Prep Week.

## Academic Policy Statements

A full list of UK academic policies is available at https://provost.uky.edu/proposals/guidance-course-proposals/standard-academic-policy-statements. Questions about these policies can be directed to the Office of the Provost.


## Academic Offenses (Cheating, Plagiarism, and Falsification or Misuse of Academic Records)

UK policies on academic offenses are available at 
https://provost.uky.edu/proposals/guidance-course-proposals/academic-offenses. For a thorough description of “plagiarism,” see https://ombud.uky.edu/students/what-plagiarism. For a thorough description of “cheating,” see https://ombud.uky.edu/students/what-cheating. Use of LLMs (so-called "AI") including such tools as ChatGPT, Claude, and Grammarly is cheating if not fully disclosed (see below).

## Resources
The university offers a variety of resources available to students. Visti the Office of Student Success to access the full list.

## Classroom Emergency Preparedness and Response 
Please see the following link for information related to emergency reporting and action: https://provost.uky.edu/curriculumproposals/syllabus-information.

## Classroom Behavior Policies

Laptops, phones, and tablets may be used only for appropriate purposes in class. Any electronic devices that are not being used for classroom activities are to be kept out of sight. NO HEADPHONES. The idea is to create as little distraction as possible – for your sake as well as mine and everyone else’s. No texting, emailing, shopping, doomscrolling social media, or other internet-type activities are allowed in class unless required by the class. If you are caught in violation of these rules, you will be asked to leave the classroom.

## Course Recordings

The University of Kentucky Code of Student Conduct defines Invasion of Privacy as using electronic or other devices to make a photographic, audio, or video record of any person without their prior knowledge or consent when such a recording is likely to cause injury or distress.

Meetings of this course may be recorded. All video and audio recordings of lecturers and class meetings, provided by the instructors, are for educational use by students in this class only. They are available only through the Canvas shell for this course and are not to be copied, shared, or redistributed.

As addressed in the Code of Student Conduct, students are expected to follow appropriate university policies and maintain the security of linkblue accounts used to access recorded class materials. Recordings may not be reproduced, shared with those not enrolled in the class, or uploaded to other online environments.

If the instructor or a University of Kentucky office plans any other uses for the recordings, beyond this class, students identifiable in the recordings will be notified to request consent prior to such use. In anticipation of such cases, students may be asked to complete an “authorization of use” form by a faculty member.

Video and audio recordings by students are not permitted during the class unless the student has received prior permission from the instructor. Any sharing, distribution, and or uploading of these recordings outside of the parameters of the class is prohibited. Students with specific recording accommodations approved by the Disability Resource Center should present their official documentation to the instructor.



## Course Copyright 

All original instructor-provided content for this course, which may include handouts, assignments, and lectures, is the intellectual property of the instructor(s). Students enrolled in the course this academic term may use the original instructor-provided content for their learning and completion of course requirements this term, but such content must not be reproduced or sold. Students enrolled in the course this academic term are hereby granted permission to use original instructor-provided content for reasonable educational and professional purposes extending beyond this course and term, such as studying for a comprehensive or qualifying examination in a degree program, preparing for a professional or certification examination, or to assist in fulfilling responsibilities at a job or internship; other uses of original instructor-provided content require written permission from the instructor(s) in advance.

## Use of Generative AI Tools (e.g. LLMs such as ChatGPT, Claude, or Grammarly)
 
For most assignments in this course, the use of GenAI to complete any part of the submitted work is prohibited unless explicitly specified by the instructor or TA. In the event that specific permission to use GenAI tools is given, it will (1) be explicitly stated, in writing, in the assignment, that such tools are allowed and (2) students _must_ acknowledge any work that is not their own. The absence of either (1) explicit permission _or_ (2) full acknowledgement by the student will be considered cheating and the student will earn zero points on the affected assignment(s). Use of these tools includes: citations for outside scholarship or information gathered from other sources, automatically paraphrasing existing work, generating text or media in response to assignment prompts, even if subsequently modified by the student, and _any_ other use of these tools. "Full acknowledgment" means that students will, through highlighting or the use of track changes (or footnotes, etc.), clearly delineate any text or media that is generated by a GenAI tool. If you have any questions or concerns about this policy, contact your instructor before submitting any assignments. See [UK-Advance instructional guidelines](https://advance.uky.edu/sites/default/files/2023-12/to%20post_UK-ADVANCE-instructional-guidelines-14Dec2023.pdf) for more information.
