---
layout: course
title:  "Lin 331 - Language in the United States"
date:   2025-04-15 17:21:16
categories: teaching sociolinguistics
---

This course is an introduction to the linguistic diversity of the United States and the role of language in the production and negotiation of various forms of social difference (e.g., ethnicity, gender, region, etc.). The course examines the ways in which language serves to construct social categories and the relationship between language and identity, emphasizing the ways in which individuals use language to present themselves as a specific type of person. The course also outlines linguistic and social implications of non-standard English dialects and multilingualism in American society. Emphasis will be given to questions of power and resistance related to language use in the contexts of government, education, and business. Students will learn how to collect information about language use and analyze it to develop informed opinions about situations in which linguistic differences have implications for issues of social equality and justice.

## Required Materials
### Textbook

- *English with an accent: Language, ideology, and discrimination in the United States, Third Edition* (ISBN 1138041939) by Rusty Barrett, Jennifer Cramer, and Kevin B. McGowan  THIRD EDITION (Routledge, 2023) [Please DO NOT try to use the first or second editions; the new edition is very different]. Readings from this book are marked as EWAA in the schedule. Please note that I am one of the 3 authors of this textbook but I will earn no royalties from your purchase as these are donated to the department.

### Additional Readings
Additional readings will be made available on Canvas (marked as C on the schedule).

## Course Goals/Objectives:
- Demonstrate an understanding of historical changes in the language diversity and shifts in the linguistic categories related to racial and ethnic categorizations in the United States
- Teach sociolinguistic approaches to analyzing forms of social and linguistic difference
- Demonstrate the equality of different dialects and the rule-based nature of all forms of language and be familiar with the basic grammar of non-standard dialects of American English
- Develop an understanding of bilingualism and the cultural and historical significance of languages other than English in the United States
- Learn the basic laws related to language rights and be able to apply them to contexts associated with education, business, and civic participation
- Learn to critically analyze language use in literary and media representations of identity and to analyze rhetorical and linguistic strategies typically found in discussions related to social difference and diversity


## Student Learning Outcomes:
Upon completion of this course, students will be able to:

- Demonstrate knowledge of the legal issues related to language differences, including laws concerning the use of languages other than English in courts and in the workplace, through detailed analysis of hypothetical situations involving language conflict.
- Acquire the ability to analyze forms of social difference based on knowledge of historical, cultural, and linguistic differences by conducting independent research on sociolinguistic issues in the United States.
- Show recognition of the ways in which linguistic differences relate to questions of social justice and civic participation through the analysis of documents related to linguistic diversity.
- Demonstrate the ability to find information related to proposed legislation concerning language policy at the state and national level and to compare language policy in different states by conducting independent research on government documents.
- Learn to analyze the language used in writing about (or discussion of) social difference in order to recognize forms of prejudice including stereotyped representations as demonstrated through the analysis of primary texts.


## Course Requirements

| Assignment             | Weight |
| ---------------------- | ------ |
| ✓ Assignments (x 5)    | 40%    |
| ✓ Participation        | 10%    |
| ✓ Midterm              | 25%    |
| ✓ Final                | 25%    |

#### ✓ Assignments
Assignments for this class (distributed via Canvas) are short activities based on the content of course lectures and reading assignments. Most of these assignments are individual efforts, though some may require students to work in groups. No cheating (including the use of generative AI) will be tolerated. There will be five (5) such assignments. Due dates for these assignments are listed in the course schedule below.

#### ✓ Exams
There will be two in-class exams: a midterm and a final. The final is not cumulative and will only cover the material after the midterm exam.

#### ✓ Participation
You are expected to attend each class and to have done the reading assigned for that day. In the course schedule, readings appear next to the day on which they are due. I recommend that you take notes on the readings and come prepared with questions or comments to contribute to class discussion. Your participation grade will be based on participation questions that are sprinkled throughout the lectures.


## Grading Practices

The grading scale for the final course grade will be as follows. Note: it is also possible to receive an Incomplete (I) as a placeholder grade if difficult, unavoidable circumstances arise during the semester that make it impossible for you to complete the course requirements before grades are due (but this has to be discussed with me in advance!).

| Final Percentage | Letter Grade |
| ---------------- | ------------ |
| 90 – 100%          | A            |
| 80 – 89%           | B            |
| 70 – 79%           | C            |
| 60 – 69%         | D            |
| Below 60%        | E            |

## Attendance Policy
In order to benefit fully from lectures and from the insights of the other students in the course (and to contribute your own), it is important that you attend every class session; if you do have to miss a class session, you must let me know the circumstances of your absence. If you have specific questions regarding any information covered in class, please come and see one of us during office hours (or schedule an appointment for another time); please do not expect us to repeat entire lectures, however.

If you need to leave early for any reason, please let us know before class starts.


## Academic Policy Statements

- [Academic Policy Statements](https://provost.uky.edu/proposals/guidance-course-proposals/standard-academic-policy-statements)
- [Mental Health Resources](https://studentsuccess.uky.edu/get-help)
- [Academic Support](https://studentsuccess.uky.edu/academicresources)
- [Disability Resource Center](https://studentsuccess.uky.edu/disability-resource-center)
- [Academic Ombud](https://ombud.uky.edu/students)
- [Classroom Emergency Preparedness and Response information](https://provost.uky.edu/instructor-resources)

## Plagiarism & Academic Integrity

- [What is Plagiarism?](https://ombud.uky.edu/students/what-plagiarism)
	Summary: Do not present others' work as your own. If you get an idea from a source, cite that source (both to show the research work you've done and to credit the people who have influenced your thinking). Buying a paper from someone, using Generative AI, or copying something from the internet are each obviously plagiarism and unacceptable, but plagiarism includes behaviors students sometimes find surprising. Paraphrasing someone else's writing in your own words (without citing them) is plagiarism. Citing something you did not read based on someone else's commentary on that book or paper is plagiarism. Be thoughtful, give credit where it is due, and do your own work and you won't have any problems.
- [What is Cheating?](https://ombud.uky.edu/students/what-cheating)
	Before taking or giving answers to a quiz, test, homework, transcription, etc. to someone else, please ask yourself what the point or value of earning a university degree _is_ if you aren't going to do the work yourself? I do _not_ look kindly on cheating which includes such insidious behaviors as taking a Canvas exam or quiz and then sharing the answers with a group chat.
- **Generative AI** use for any assignment is strictly prohibited.
	Idea generation, analytical thinking, and critical analysis are key outcomes in this course. As a result, all assignments submitted by the student must be 100% their original work. Generative AI tools, including Grammarly, should not be used for any stage of any assignment or activity. Any submission of AI-generated content (even if you paraphrase the output) will be considered misuse in the context of this course and consequences will follow University policies. See the [University Senate guidelines found here](https://www.uky.edu/universitysenate/ao). Beyond this, Generative AI is _terrible_ at phonetics and phonology. I guarantee you can do a better job yourself.
- [Academic Misconduct Process](https://ombud.uky.edu/students/academic-misconduct-process)
  

## Course Outline (subject to change)
z
- January 14, 2025 (Tuesday)
	- Introduction, review syllabus	
- January 16, 2025 (Thursday)
	- Introduction to Language Ideologies
	- EWAA, Chapter 1
- January 21, 2025 (Tuesday)
	- Language, categorization, & social identities
	- EWAA, Chapter 2
- January 23, 2025 (Thursday)
	- A quick introduction to Language & Linguistics
	- EWAA, Chapter 3
	- **Assignment #1 Due**
- January 28, 2025 (Tuesday)
	- Language subordination
	- EWAA, Chapter 4
- January 30, 2025 (Thursday)
- February 4, 2025 (Tuesday)
	- American accents
	- EWAA, Chapter 5
- February 6, 2025 (Thursday)
	- **Assignment #2 Due**
- February 11, 2025 (Tuesday)
	- Language, racialization, & race
	- EWAA, Chapter 6
- February 13, 2025 (Thursday)
- February 18, 2025 (Tuesday)
	- Non-English spoken languages in the US
	- EWAA, Chapter 7
- February 20, 2025 (Thursday)
- February 25, 2025 (Tuesday)
	- American Sign Language
	- EWAA, Chapter 8
- February 27, 2025 (Thursday)
- March 4, 2025 (Tuesday)
	- Perceptual dialectology
	- EWAA, Chapter 9
- March 6, 2025 (Thursday)
	- **Assignment #3 Due**
- March 11, 2025 (Tuesday)
  - First half wrap-up, Exam Prep
- March 13, 2025 (Thursday)
	- **Midterm Exam**
- March 18, 2025 (Tuesday)
	- *Spring Break*
- March 20, 2025 (Thursday)
	- *Spring Break*
- March 25, 2025 (Tuesday)
	- A history of 'r' in the US
	- EWAA, Chapter 10
- March 27, 2025 (Thursday)
- April 1, 2025 (Tuesday)
	- Language in education
	- EWAA, Chapter 11
- April 3, 2025 (Thursday)
	- **Assignment #4 Due**
- April 8, 2025 (Tuesday)
	- Language in the media
	- EWAA, Chapter 12
- April 10, 2025 (Thursday)
- April 15, 2025 (Tuesday)
	- Language in the workplace
	- EWAA, Chapter 13
- April 17, 2025 (Thursday)
	- **Assignment #5 Due**
- April 22, 2025 (Tuesday)
	- Language in the law
	- EWAA, Chapter 14
- April 24, 2025 (Thursday)
- April 29, 2025 (Tuesday)
	- Stereotype as cognitive template
	- Lindeman 2002 (C)
	- McGowan 2015 (C)

- May 8, 2025 (Thursday)
	- [Final Exam](https://registrar.uky.edu/calendars/examination-schedules)
	- 8:00 - 10:00am, in person


## Course Copyright

All original instructor-provided content for this course, which may include handouts, assignments, and lectures, is the intellectual property of the instructor(s). Students enrolled in the course this academic term may use the original instructor-provided content for their learning and completion of course requirements this term, but such content must not be reproduced or sold. Students enrolled in the course this academic term are hereby granted permission to use original instructor-provided content for reasonable educational and professional purposes extending beyond this course and term, such as retaining for your own personal use, studying for a comprehensive or qualifying examination in a degree program, preparing for a professional or certification examination, or to assist in fulfilling responsibilities at a job or internship; other uses of original instructor-provided content require written permission from the instructor(s) in advance.