---
title: "teaching"
css: simple.css
listing: 
  - id: advising
    type: table
    contents: "advisees/*.qmd"
    field-links: [thesis, advisee]
    fields: [year, advisee, thesis, role]
    sort:
      - year desc
      - lastname asc
    table-hover: true
  - id: courses-uk
    contents: "courses-uk/*.qmd"
    type: default
    sort: "date desc" # can also sort on more than one field
    categories: true # allows you to sort posts by assigned categories 
  - id: courses-lsa
    contents: "courses-lsa/*.qmd"
    type: default
    sort: "date desc" # can also sort on more than one field
    categories: true # allows you to sort posts by assigned categories 
---

## Teaching Philosophy

Not only are we the part of the universe that can think about itself but, even as tiny children, we possess the ability to move those thoughts from the privacy of our own minds and *into the minds* of the people around us! The fact that we do this by flapping bits of meat and bone around in our heads and gently exhaling over them should shock each of us. Recognizing that this human capacity is bizarre, complex, and puzzling despite its effortlessness is the first step for many students to recognizing that science is not intimidating and esoteric, but is directly and fascinatingly about us. Linguistics, perhaps uniquely among disciplines, sits at the boundary of the humanities, the physical sciences, and the social sciences to provide a scaffolding for understanding what it is to be human. Linguistics calls to students, it inspires them to be inquisitive, and it allows me to teach them quantitative and qualitative methods for an empirical engagement with the world we inhabit together.

What I hope every student learns from me, in the classroom or out, is the joy of discovery and the necessity of failure on the path to discovery. I strive to build classes that provide structured access to knowledge and the encouragement for students to explore and synthesize that knowledge themselves. I want to engender a healthy distrust for the obvious while feeding or reviving an innate respect for the wondrous complexity that surrounds us. In practical terms this means things like curating assigned readings and providing support for them so that a curious reader can discover, for themselves, a coherent path. I provide assignments, and grading structure, that encourage play and the kind of low-stakes opportunities to experience failure and recovery from failure that are necessary for learning.

Failure, while normal and necessary, is also frightening and painful.  For our top-performing students who maybe have never gotten a grade lower than an &lsquo;A&rsquo;, failure is unthinkable.  For students who, for whatever reason, are struggling to believe they belong here, failure is also unthinkable.  It may be the one thing they have in common, and it holds them all back, in their own ways, from getting the most out of this precious opportunity to earn a degree.

An emphasis on discovery and synthesis can be unsettling for students, especially first year students, accustomed to memorizing and regurgitating information. One student in my second semester at Kentucky wrote in my evaluations, ``The setup of this class was very confusing to me as far as knowing how to pay attention/take notes/study. It seemed like more of a series of meetings where we get together and talk about linguistics in the world around us, but it was extremely difficult to decide what was important to pay attention to...''. In one sense, this is precisely the kind of discomfort I am trying to engender in students! This is the voice of a student struggling with ideas that are slightly out of their reach. Still, it buys them nothing if I carefully construct a classroom that encourages active exploration and they're left feeling unmoored and anxious. So in subsequent semesters I have made a point of addressing that anxiety by highlighting the idea of the day and emphasizing that the course is what emerges from our collaboration: from their reading and thinking outside of class, from my preparation of materials, and from our shared investigation of the questions and ideas in those materials. They will be evaluated fairly on their ability to synthesize, rather than repeat, ideas, and that practicing this synthesis in class discussions or in their work groups is an ideal way to get better at it. In other words, the experience of talking about linguistics in the world around us \emph{is} the part to pay attention to.


## Mentorship & Advising

When advising research I try to strike a balance between providing support while still allowing the student to experience a manageable amount of struggle and frustration. I support by providing guidance with research questions, methodology, data analysis, etc. and I help the student learn to structure their research by setting deadlines and holding status meetings with, I hope, clear expectations. But research is difficult and it is a disservice to undergraduates and especially to graduate students to shield them from that difficulty. Most of my advisees have come to me at some point in the hopes that I would write some piece of code, do some statistical analysis, or otherwise fix some problem for them. Unfortunately, I have occasionally stepped in and done as asked, but in retrospect it is clear that the students I over-helped ultimately fared worse than the students I made to work it out on their own. Students have gone on to write brilliant theses after I'd left the program (Penelope Howe, Rice PhD 2017), or pursue doctoral work at Indiana (Kait Lee); Michigan (Kelly Wright); Delaware (Aidah Aljuran); Ohio State (Kyler Laycock); or Kentucky (Stella Takvoryan). I am not taking credit for their accomplishments; quite the opposite, I see my my role as an advisor as supporting these future colleagues just enough that they understand all of the credit is justly and rightfully their own.

:::{#advising}
:::

## Selected Courses at the University of Kentucky

:::{#courses-uk}
:::

## Courses at Linguistic Institutes

:::{#courses-lsa}
:::

